In [6]:

import pandas as pd
# Define the employee data
data = {
    'Name': ['Employee_1', 'Employee_2', 'Employee_3', 'Employee_4', 'Employee_5', 
             'Employee_6', 'Employee_7', 'Employee_8', 'Employee_9', 'Employee_10', 
             'Employee_11', 'Employee_12', 'Employee_13', 'Employee_14', 'Employee_15', 
             'Employee_16', 'Employee_17', 'Employee_18', 'Employee_19', 'Employee_20', 
             'Employee_21', 'Employee_22', 'Employee_23', 'Employee_24', 'Employee_25', 
             'Employee_26', 'Employee_27', 'Employee_28', 'Employee_29', 'Employee_30'],
    'Salary': [54895.0, 38784.0, 120000.0, 60309.0, 46788.0, 
               50598.0, 61915.0, 50651.0, 38155.0, 55480.0, 
               49396.0, 64183.0, 38894.0, 46672.0, 20000.0, 
               57935.0, 57055.0, 44719.0, 66267.0, 48339.0, 
               44490.0, 48817.0, 39738.0, 59433.0, 80823.0, 
               80000.0, 52704.0, 54168.0, 56569.0, 45481.0],
    'Age': [49, 48, 34, 33, 59, 36, 34, 30, 36, 29, 
            29, 54, 55, 29, 53, 34, 23, 41, 58, 41, 
            45, 22, 39, 47, 22, 30, 53, 33, 23, 52],
    'Function': ['HR', 'Sales', 'Manager', 'Manager', 'HR', 
                 'Sales', 'Manager', 'HR', 'Sales', 'HR', 
                 'Sales', 'Developer', 'Developer', 'Sales', 'HR', 
                 'Sales', 'Developer', 'Developer', 'HR', 'Sales', 
                 'HR', 'Manager', 'HR', 'Sales', 'HR', 'Sales', 
                 'Sales', 'Developer', 'Developer', 'HR']
}

# Convert to DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

# Define the department to code mapping
department_mapping = {
    'HR': 'HR001',
    'Sales': 'SAL002',
    'Manager': 'MGR003',
    'Developer': 'DEV004'
}

# Convert the dictionary to a DataFrame
department_df = pd.DataFrame(list(department_mapping.items()), columns=['Department', 'Department_Code'])

# Display the DataFrame
print(department_df)

           Name    Salary  Age   Function
0    Employee_1   54895.0   49         HR
1    Employee_2   38784.0   48      Sales
2    Employee_3  120000.0   34    Manager
3    Employee_4   60309.0   33    Manager
4    Employee_5   46788.0   59         HR
5    Employee_6   50598.0   36      Sales
6    Employee_7   61915.0   34    Manager
7    Employee_8   50651.0   30         HR
8    Employee_9   38155.0   36      Sales
9   Employee_10   55480.0   29         HR
10  Employee_11   49396.0   29      Sales
11  Employee_12   64183.0   54  Developer
12  Employee_13   38894.0   55  Developer
13  Employee_14   46672.0   29      Sales
14  Employee_15   20000.0   53         HR
15  Employee_16   57935.0   34      Sales
16  Employee_17   57055.0   23  Developer
17  Employee_18   44719.0   41  Developer
18  Employee_19   66267.0   58         HR
19  Employee_20   48339.0   41      Sales
20  Employee_21   44490.0   45         HR
21  Employee_22   48817.0   22    Manager
22  Employee_23   39738.0   39         HR
23  Employee_24   59433.0   47      Sales
24  Employee_25   80823.0   22         HR
25  Employee_26   80000.0   30      Sales
26  Employee_27   52704.0   53      Sales
27  Employee_28   54168.0   33  Developer
28  Employee_29   56569.0   23  Developer
29  Employee_30   45481.0   52         HR
  Department Department_Code
0         HR           HR001
1      Sales          SAL002
2    Manager          MGR003
3  Developer          DEV004

In [7]:
# Q1: Create a new column Age_Bucketed
def bucket_age(age):
    if age < 20:
        return '<20 years'
    elif 20 <= age <= 30:
        return '20-30 years'
    elif 30 <= age <= 40:
        return '30-40 years'
    elif 40 <= age <= 50:
        return '40-50 years'
    else:
        return '>50 years'

df['Age_Bucketed'] = df['Age'].apply(bucket_age)
df.head(5)

         Name    Salary  Age Function Age_Bucketed
0  Employee_1   54895.0   49       HR  40-50 years
1  Employee_2   38784.0   48    Sales  40-50 years
2  Employee_3  120000.0   34  Manager  30-40 years
3  Employee_4   60309.0   33  Manager  30-40 years
4  Employee_5   46788.0   59       HR    >50 years

In [8]:

# Q2: Create a new column to generate function codes for each function using department_df
df = df.merge(department_df, left_on='Function', right_on='Department', how='left')
df.drop(columns=['Department'], inplace=True)
df.head(5)

         Name    Salary  Age Function Age_Bucketed Department_Code
0  Employee_1   54895.0   49       HR  40-50 years           HR001
1  Employee_2   38784.0   48    Sales  40-50 years          SAL002
2  Employee_3  120000.0   34  Manager  30-40 years          MGR003
3  Employee_4   60309.0   33  Manager  30-40 years          MGR003
4  Employee_5   46788.0   59       HR    >50 years           HR001

In [9]:
# Q3: Create a new column to find outliers in the df: "Outlier", "Not an Outlier"
Q1 = df['Salary'].quantile(0.25)
Q3 = df['Salary'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

def detect_outlier(salary):
    if salary < lower_bound or salary > upper_bound:
        return 'Outlier'
    else:
        return 'Not an Outlier'

df['Outlier'] = df['Salary'].apply(detect_outlier)
df.head(5)

,Name,Salary,Age,Function,Age_Bucketed,Department_Code,Outlier
0,Employee_1,54895.0,49,HR,40-50 years,HR001,Not an Outlier
1,Employee_2,38784.0,48,Sales,40-50 years,SAL002,Not an Outlier
2,Employee_3,120000.0,34,Manager,30-40 years,MGR003,Outlier
3,Employee_4,60309.0,33,Manager,30-40 years,MGR003,Not an Outlier
4,Employee_5,46788.0,59,HR,>50 years,HR001,Not an Outlier